# Generated by Django 3.0.3 on 2020-03-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='Url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
