# Generated by Django 3.0.3 on 2020-03-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_cursosv2_docentesv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngenieriaV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingenieria', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cursosv2',
            name='Docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.DocentesV2'),
        ),
        migrations.AlterField(
            model_name='docentesv2',
            name='Docente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
