# Generated by Django 3.0.3 on 2020-03-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200317_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aula', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CursosList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora', models.TimeField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cursosv2',
            name='Ingenieria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.IngenieriaV2'),
        ),
        migrations.AlterField(
            model_name='cursosv2',
            name='Aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Aulas'),
        ),
        migrations.AlterField(
            model_name='cursosv2',
            name='Curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CursosList'),
        ),
        migrations.AlterField(
            model_name='cursosv2',
            name='Fecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Fechas'),
        ),
        migrations.AlterField(
            model_name='cursosv2',
            name='Hora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Horas'),
        ),
    ]
