# Generated by Django 3.0.3 on 2020-03-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200317_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechas',
            name='Text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horas',
            name='Text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
