# Generated by Django 3.0.3 on 2020-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200317_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosv2',
            name='IdCurso',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
