# Generated by Django 3.0.3 on 2020-03-17 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_cursosv2_idcurso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursosv2',
            old_name='IdCurso',
            new_name='NumCursos',
        ),
    ]
