# Generated by Django 3.0.3 on 2020-03-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200317_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursosv2',
            old_name='IdCursos',
            new_name='IdCurso',
        ),
    ]
